In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.12.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [7]:
x_train.size

47040000

In [9]:
x_test

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [10]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [11]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.8533933 , -0.8404922 ,  0.08533923,  0.07667631,  0.05577266,
        -0.6317625 ,  0.03432064, -0.36561567, -0.72825074,  0.02609657]],
      dtype=float32)

In [12]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.8533933 , -0.8404922 ,  0.08533923,  0.07667631,  0.05577266,
        -0.6317625 ,  0.03432064, -0.36561567, -0.72825074,  0.02609657]],
      dtype=float32)

In [13]:
tf.nn.softmax(predictions).numpy()

array([[0.24016938, 0.04414408, 0.11141816, 0.11045712, 0.10817213,
        0.05439045, 0.10587633, 0.07097555, 0.04938765, 0.10500917]],
      dtype=float32)

In [14]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [15]:
loss_fn(y_train[:1], predictions).numpy()

2.9115667

In [16]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [19]:
model.fit(x_train, y_train, epochs=20)

Epoch 1/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0674 - accuracy: 0.9780
Epoch 2/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0592 - accuracy: 0.9806
Epoch 3/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0528 - accuracy: 0.9830
Epoch 4/20
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0468 - accuracy: 0.9843
Epoch 5/20
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0444 - accuracy: 0.9852
Epoch 6/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0412 - accuracy: 0.9859
Epoch 7/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0380 - accuracy: 0.9876
Epoch 8/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0360 - accuracy: 0.9881
Epoch 9/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0340 - accuracy: 0.9887
Epoch 10/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.031

In [21]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0966 - accuracy: 0.9796 - 470ms/epoch - 2ms/step


[0.09656765311956406, 0.9796000123023987]

In [23]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [24]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.0876061e-10, 3.8662395e-17, 2.5299485e-09, 1.6271623e-07,
        1.0546265e-18, 6.1281957e-15, 1.3591632e-23, 9.9999988e-01,
        2.8959300e-12, 1.3294379e-10],
       [1.1617077e-22, 1.5554605e-09, 1.0000000e+00, 6.4000671e-14,
        2.1875868e-37, 6.0296158e-13, 4.0584155e-12, 3.0787907e-33,
        6.7694259e-19, 6.5870422e-24],
       [9.6360394e-12, 9.9997127e-01, 3.7232532e-08, 4.0324108e-09,
        3.6460124e-06, 5.7375225e-09, 1.8444038e-07, 2.4028232e-05,
        8.5249394e-07, 1.2210898e-10],
       [1.0000000e+00, 1.8194678e-17, 4.0676595e-09, 4.0082943e-13,
        9.1078384e-18, 5.1728292e-14, 1.3868197e-11, 2.3866161e-12,
        2.1543003e-18, 1.4555614e-10],
       [3.2962860e-10, 9.6295924e-21, 6.7752180e-12, 9.6807534e-13,
        9.9992847e-01, 2.2922254e-13, 4.4548028e-12, 1.9341799e-07,
        1.1921597e-12, 7.1293791e-05]], dtype=float32)>